### ISSUE TITLE
Stuck in ESC menu

### ISSUE THREAD

**Issue by RadioactivePotato** [PrecisionClient/PrecisionClient#11] opened 2022-11-10 16:09 UTC
All buttons in the ESC menu work normally but the back to game button doesn't respond apart from the clicky sound effect.
Disconnecting from the game and reconnecting to the server doesn't solve the issue
Deloading the page doesn't solve the issue either.

**Comment by etcherfx** [comment] 2022-11-10 18:21
I got into the same problem when I opted out of arc.io. You could host your own instance on repl or something and remove the arc.io widget or you can wait for me to finish beta_0.2 and make a release zip and a deployable version on hosting sites

**Comment by etcherfx** [comment] 2022-11-10 18:22
duplicate of #6

**Closed by etcherfx** 2022-11-10 18:22 UTC
